server:
  port: 5050

spring:
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/devdb
    username: root
    password: Giulio2002@
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    rest:
      base-path: /api